name:                players-perfect
version:             0.0.0.0
description:         Please see the README

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: lib
  dependencies:
    - MonadRandom
    - aeson
    - array
    - game
    - bytestring
    - containers
    - deepseq
    - directory
    - mtl
    - random
    - random-shuffle
    - scientific
    - split
    - stm
    - text
    - time
    - transformers
    - unordered-containers
    - uuid
